<?php

namespace modava\iway\models\table;

use cheatsheet\Time;
use modava\iway\components\MyIwayModel;
use Yii;

class CustomerTable extends MyIwayModel
{
    public static function tableName()
    {
        return 'iway_customer';
    }


    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
