<?php
namespace modava\iway\components;

use backend\components\MyController;
use Yii;
use yii\web\Response;

class MyIwayController extends MyController
{
    public $model = null;

    public function init()
    {
        // Set default TimeZone
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionGetByKeyWord($q = null, $id = null)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];

        if (!is_null($q)) {
            $out = $this->model::getByKeyWord($q);
        } elseif ($id > 0) {
            $record = $this->model::findOne($id);
            if ($record) {
                $out['results'] = ['id' => $id, 'text' => $record->title];
            }
        }
        return $out;
    }
}
