<?php
namespace modava\iway\components;

use backend\components\MyController;

class MyIwayController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
